const getters = {
  //user
  token: state => state.user.token,
  userInfo: state => state.user.userInfo,
  userInfoUpdate: state => state.user.userInfoUpdate,
  isSuperUser: state => state.user.isSuperUser,
  userDeptName: state => state.user.userDeptName,
  isLogin: state => state.user.isLogin,
  isAdmin: state => state.user.isAdmin,
  userRouterInfo: state => state.user.userRouterInfo,
  addRouters: state => state.user.addRouters,
  freshMenu: state => state.user.freshMenu,
  controlShare: state => state.user.controlShare,
  //map
  map_style: state => state.map.map_style,
  mapbox_map: state => state.map.mapbox_map,
  ledger_map: state => state.map.ledger_map,
  local_map: state => state.map.local_map,
  city_map: state => state.map.city_map,
  macro_map: state => state.map.macro_map,
  plate_color: state => state.map.plate_color,
  ledgendColor: state => state.map.ledgendColor,
  addLedgerInfo: state => state.map.addLedgerInfo,
  curentPlate: state => state.map.curentPlate,
  enclosure: state => state.map.enclosure,
  enclosureCoor: state => state.map.enclosureCoor,
  ledgerDraw: state => state.map.ledgerDraw,
  mapIsload: state => state.map.mapIsload,
  cityMapIsload: state => state.map.cityMapIsload,
  macroMapIsload: state => state.map.macroMapIsload,
  situationMap:state =>state.map.situationMap,
  houseDataMap:state =>state.map.houseDataMap,
  //common
  cityList: state => state.common.cityList,
  cityCode: state => state.common.cityCode,
  plateData: state => state.common.plateData,
  plateGEOJSON: state => state.common.plateGEOJSON,
  curMenu: state => state.common.curMenu,
  plateCenter: state => state.common.plateCenter,
  userMenu: state => state.common.userMenu,
  userMenuList: state => state.common.userMenuList,
  analysistoolsUrl: state => state.common.analysistoolsUrl,
  //landmap
  fileIsimport: state => state.landmap.fileIsimport,
  curLandCoords: state => state.landmap.curLandCoords,
  curLandId: state => state.landmap.curLandId,
  curLandSaleInfo: state => state.landmap.curLandSaleInfo,
  showMessage: state => state.landmap.showMessage,
  showFriends: state => state.landmap.showFriends,
  customState: state => state.landmap.customState,
  measureState: state => state.landmap.measureState,
  hasMessage: state => state.landmap.hasMessage,
  shareInfo: state => state.landmap.shareInfo,
  freshFmFlag: state => state.landmap.freshFmFlag,
  createLandFlag: state => state.landmap.createLandFlag,
  freshSelf: state => state.landmap.freshSelf,
  plModifyId: state => state.landmap.plModifyId,
  cmNotice: state => state.landmap.cmNotice,
  landTypeTab: state => state.landmap.landTypeTab,
  landlistFlag: state => state.landmap.landlistFlag,
  popType: state => state.landmap.popType,
}
export default getters