const getters = {
  //user
  token: state => state.user.token,
  userInfo: state => state.user.userInfo,
  //map
  map_style: state => state.map.map_style,
  mapbox_map: state => state.map.mapbox_map,
  baseLayerMap: state => state.map.baseLayerMap,
  ledger_map: state => state.map.ledger_map,
  plategrade_map: state => state.map.plategrade_map,
  pointgrade_map: state => state.map.pointgrade_map,
  condition_map: state => state.map.condition_map,
  population_map: state => state.map.population_map,
  reportAdd_map: state => state.map.reportAdd_map,
  reportBase_map: state => state.map.reportBase_map,
  CD_map: state => state.map.CD_map,
  plate_color: state => state.map.plate_color,
  ledgendColor: state => state.map.ledgendColor,
  addLedgerInfo: state => state.map.addLedgerInfo,
  curentPlate: state => state.map.curentPlate,
  enclosure: state => state.map.enclosure,
  enclosureCoor: state => state.map.enclosureCoor,
  ledgerDraw: state => state.map.ledgerDraw,
  //common
  cityList: state => state.common.cityList,
  cityCode: state => state.common.cityCode,
  plateData: state => state.common.plateData,
  plateGEOJSON: state => state.common.plateGEOJSON,
  curMenu: state => state.common.curMenu,
  plateCenter: state => state.common.plateCenter,
  userMenu: state => state.common.userMenu,
  userMenuList: state => state.common.userMenuList,
  analysistoolsUrl: state => state.common.analysistoolsUrl,
  //dataquery
  classification: state => state.dataquery.classification,
  classificationObj: state => state.dataquery.classificationObj,
  plateArr: state => state.dataquery.plateArr,
  plateType: state => state.dataquery.plateType,
  classBoxFlag: state => state.dataquery.classBoxFlag,
  queryMenuIndex: state => state.dataquery.queryMenuIndex,
  isListedLand: state => state.dataquery.isListedLand,
  cardFlag: state => state.dataquery.cardFlag,
  plateID: state => state.dataquery.plateID,
  //locaitonResearch
  progress:state => state.locationResearch.progress,
  locationId:state =>state.locationResearch.locationId,
  point:state =>state.locationResearch.point,
  circleTime:state =>state.locationResearch.circleTime,
  map:state =>state.locationResearch.map,
}
export default getters